modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="administrator_authorization"
version="1.0.0"
displayName="Administrator Authorization"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="bliss, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.administrator_authorization]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration